-- MySQL Script generated by MySQL Workbench
-- Tue Jan  7 17:10:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_internet` DEFAULT CHARACTER SET utf8 ;
USE `empresa_internet` ;

-- -----------------------------------------------------
-- Table `empresa_internet`.`planes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`planes` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`planes` (
  `plan_id` INT NOT NULL AUTO_INCREMENT,
  `velocidad_megas` DOUBLE NOT NULL,
  `precio` DOUBLE NOT NULL,
  `descuento` INT NOT NULL,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`clientes` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`clientes` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(75) NOT NULL,
  `apellido` VARCHAR(75) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `provincia` VARCHAR(50) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `plan_id` INT NOT NULL,
  PRIMARY KEY (`dni`),
  INDEX `fk_clientes_planes_idx` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_planes`
    FOREIGN KEY (`plan_id`)
    REFERENCES `empresa_internet`.`planes` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
