INSERT INTO joyas (nombre, material, peso, particularidad, posee_piedra, venta_o_no)
VALUES ('Anillo de compromiso', 'Oro', 15.5, 'Anillo con diamante central', TRUE, TRUE),
       ('Collar de perlas', 'Perlas', 20.0, 'Collar clásico de perlas blancas', FALSE, TRUE),
       ('Pulsera de plata', 'Plata', 10.5, 'Pulsera de diseño sencillo', FALSE, TRUE),
       ('Aretes de oro', 'Oro', 3.2, 'Aretes pequeños con diamantes', TRUE, TRUE),
       ('Reloj de lujo', 'Acero inoxidable', 75.0, 'Reloj con detalles en oro', FALSE, TRUE),
       ('Anillo de rubí', 'Oro', 8.0, 'Anillo con rubí en el centro', TRUE, TRUE),
       ('Collar de diamantes', 'Platino', 30.0, 'Collar con diamantes incrustados', TRUE, TRUE),
       ('Pulsera de cuero', 'Cuero', 12.0, 'Pulsera de diseño moderno con detalles metálicos', FALSE, TRUE),
       ('Aretes de plata', 'Plata', 4.0, 'Aretes en forma de flor', FALSE, TRUE),
       ('Anillo de esmeralda', 'Oro blanco', 9.0, 'Anillo con esmeralda verde', TRUE, TRUE),
       ('Collar de esmeraldas', 'Oro amarillo', 50.0, 'Collar largo con esmeraldas y diamantes', TRUE, TRUE),
       ('Reloj de plata', 'Plata', 60.0, 'Reloj con correa de cuero', FALSE, TRUE),
       ('Anillo de zafiro', 'Oro rosado', 7.0, 'Anillo con zafiro azul', TRUE, TRUE),
       ('Pulsera de diamantes', 'Platino', 22.5, 'Pulsera con diamantes pequeños', TRUE, TRUE),
       ('Collar de oro', 'Oro', 25.0, 'Collar elegante de oro sólido', FALSE, TRUE),
       ('Aretes de esmeralda', 'Oro amarillo', 5.0, 'Aretes con esmeraldas y diamantes', TRUE, TRUE),
       ('Anillo de titanio', 'Titanio', 5.0, 'Anillo resistente con diseño futurista', FALSE, FALSE),
       ('Reloj de madera', 'Madera', 50.0, 'Reloj de madera con detalles en acero', FALSE, TRUE),
       ('Collar con piedra lunar', 'Plata', 15.0, 'Collar con piedra lunar brillante', TRUE, TRUE),
       ('Aretes de perlas', 'Oro blanco', 6.0, 'Aretes de perlas con detalles de oro', FALSE, TRUE);
