-- MySQL Script generated by MySQL Workbench
-- Tue Jan  7 15:46:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_internet` DEFAULT CHARACTER SET utf8 ;
USE `empresa_internet` ;

-- -----------------------------------------------------
-- Table `empresa_internet`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`Client` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`Client` (
  `dni` INT NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(45) NULL,
  `birth_date` DATETIME NULL,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`plan` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`plan` (
  `idplan` INT NOT NULL,
  `speed_mb` INT NULL,
  `price` DECIMAL(10) NULL,
  `discount` DECIMAL(10) NULL,
  PRIMARY KEY (`idplan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`client_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`client_plan` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`client_plan` (
  `id` INT NOT NULL,
  `client_dni` INT NULL,
  `plan_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `client_dni_idx` (`client_dni` ASC) VISIBLE,
  INDEX `idplan_idx` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `client_dni`
    FOREIGN KEY (`client_dni`)
    REFERENCES `empresa_internet`.`Client` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idplan`
    FOREIGN KEY (`plan_id`)
    REFERENCES `empresa_internet`.`plan` (`idplan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
