-- MySQL Script generated by MySQL Workbench
-- Tue Jan  7 17:30:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_internet` DEFAULT CHARACTER SET utf8 ;
USE `empresa_internet` ;

-- -----------------------------------------------------
-- Table `empresa_internet`.`internet_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`internet_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speed_in_mb` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `discount` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_internet`.`client` (
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `birth_date` DATE NOT NULL,
  `dni` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `internet_plan_id` INT NULL,
  INDEX `internet_plan_id_idx` (`internet_plan_id` ASC) VISIBLE,
  PRIMARY KEY (`dni`, `birth_date`),
  CONSTRAINT `internet_plan_id`
    FOREIGN KEY (`internet_plan_id`)
    REFERENCES `empresa_internet`.`internet_plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
