SELECT EPISODES.*
FROM EPISODES
         INNER JOIN SEASONS ON EPISODES.SEASON_ID = SEASONS.ID
         INNER JOIN SERIES ON SEASONS.SERIE_ID = SERIES.ID
WHERE SERIES.TITLE = 'The Walking Dead';

SELECT *
FROM TWD
         INNER JOIN SEASONS ON TWD.SEASON_ID = SEASONS.ID
WHERE SEASONS.NUMBER = 1;

DROP INDEX SEASON_IDX ON SEASONS;

EXPLAIN SELECT * FROM SEASONS WHERE NUMBER = 9;

CREATE INDEX SEASON_IDX ON SEASONS(NUMBER);

EXPLAIN SELECT * FROM SEASONS WHERE NUMBER = 9;

SHOW INDEX FROM SEASONS;
