create table siniestros (id bigint generated by default as identity, fecha date, perdida_economica float(53), vehiculo_id bigint not null, primary key (id))
create table vehiculos (id bigint generated by default as identity, cantidad_ruedas integer, fabricacion date, marca varchar(20), modelo varchar(30), patente varchar(20), primary key (id))
alter table if exists siniestros add constraint FKfqmqval6gmj723jjq4pcr9xg0 foreign key (vehiculo_id) references vehiculos
